### ISSUE TITLE
no example method `init_websocket`, no doced driver methods

### ISSUE THREAD

**Issue by ArtemIsmagilov** [embl-bio-it/python-mattermost-autodriver#12]
According to the README, it is not very clear exactly how to use websocket. Can we add this example to the README and documentation? I think it will be difficult for developers to delve into the sources. The documentation contains information on endpoints, but I did not see the driver methods. Could I have missed something?

**Comment by ArtemIsmagilov** [comment]
Well, I'm not attentive. I apologize for my stupidity.
https://embl-bio-it.github.io/python-mattermost-autodriver/#mattermostautodriver.Driver.init_websocket

**Comment by unode** [comment]
Hi @ArtemIsmagilov

Our documentation is currently rather limited and lacking some simple examples.
If you have suggestions they are very much welcome.
