### ISSUE TITLE
setup.py install_requires may have a syntax error

### ISSUE THREAD

**Issue by agoertz-fls** [embl-bio-it/python-mattermost-autodriver#3]
Hi,
from the documentation at https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/ I will quote here an example:

```
install_requires=[
   'A>=1,<2',
   'B>=2'
]
```

It looks like there should be a comma between the two requirement specifications in your code it looks like this

```
install_requires=[
        'aiohttp>=3.8.1<4.0.0',
        'httpx>=0.20.0<1.0.0',
    ],
```

and this throws off my poetry process with

```
Resolving dependencies... (0.3s)Invalid requirement (aiohttp (>=3.8.1<4.0.0)) found in mattermostautodriver-1.2.2 dependencies, skipping
Invalid requirement (httpx (>=0.20.0<1.0.0)) found in mattermostautodriver-1.2.2 dependencies, skipping
```

Could you fix this to
```
install_requires=[
        'aiohttp>=3.8.1, <4.0.0',
        'httpx>=0.20.0, <1.0.0',
    ],
```

Kind regards,
Alex

**Comment by unode** [comment]
Thanks for reporting, now fixed in the main branch.
I'll make a patch release as soon I can.
