### ISSUE TITLE
version 1.2.3 is not released

### ISSUE THREAD

**Issue by aminiun** [embl-bio-it/python-mattermost-autodriver#4]
Hi!

I was checking about `install_requires` syntax issue fix, and saw that it is fixed in 1.2.3 version.

But apparently it's not released in Pypi yet. Any plan for that ?

**Comment by unode** [comment]
Hi @aminiun 

Apologies, there was a GitHub Action failure and 1.2.3 wasn't pushed to PyPi.
Meanwhile some other changes accumulated so I just released 1.2.4 with the mentioned fix [and more](https://github.com/embl-bio-it/python-mattermost-autodriver/blob/main/CHANGELOG.rst#124).

Feel free to reopen if that release doesn't fix your problem.

Cheers,
Renato
