### ISSUE TITLE
DEBUG=True in Driver()

### ISSUE THREAD

**Issue by ArtemIsmagilov** [embl-bio-it/python-mattermost-autodriver#5]
Careful!!
Setting debug to True, will reveal your password in the log output if you do driver.login()!
This is NOT for production!
Traceback (most recent call last):
  File "test1.py", line 112, in <module>
    test5()
  File "test1.py", line 79, in test5
    bot = Driver({
          ^^^^^^^^
  File "venv/lib/python3.11/site-packages/mattermostautodriver/driver.py", line 119, in __init__
    super().__init__(options, client_cls)
  File "venv/lib/python3.11/site-packages/mattermostautodriver/driver.py", line 109, in __init__
    self.client = client_cls(self.options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/mattermostautodriver/client.py", line 191, in __init__
    super().__init__(options)
  File "venv/lib/python3.11/site-packages/mattermostautodriver/client.py", line 31, in __init__
    self.activate_verbose_logging()
  File "venv/lib/python3.11/site-packages/mattermostautodriver/client.py", line 51, in activate_verbose_logging
    httpx_log.setLevel("TRACE")
  File "/usr/lib/python3.11/logging/__init__.py", line 1464, in setLevel
    self.level = _checkLevel(level)
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 207, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'TRACE'

How fix?

**Comment by ArtemIsmagilov** [comment]
you rushed to close the answer

**Comment by unode** [comment]
This fixed one bug but there's another affecting debugging. Ironic.

**Comment by unode** [comment]
And it looks like there's another bug in `httpx` because their documentation:

```
import logging
import httpx

logging.basicConfig(
    format="%(levelname)s [%(asctime)s] %(name)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.DEBUG
)

httpx.get("https://www.example.com")
```

only returns:

```
DEBUG [2023-08-16 18:40:37] httpx - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG [2023-08-16 18:40:37] httpx - load_verify_locations cafile='.venv/lib/python3.10/site-packages/certifi/cacert.pem'
INFO [2023-08-16 18:40:38] httpx - HTTP Request: GET https://www.example.com "HTTP/1.1 200 OK"
```

using `httpx 0.24.1` and `httpcore 0.16.3`.

Upgrading to `httpcore 0.17.3` gives the expected output:

```
DEBUG [2023-08-16 18:44:42] httpx - load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG [2023-08-16 18:44:42] httpx - load_verify_locations cafile='.venv/lib/python3.10/site-packages/certifi/cacert.pem'
DEBUG [2023-08-16 18:44:42] httpcore.connection - connect_tcp.started host='www.example.com' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG [2023-08-16 18:44:42] httpcore.connection - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f80034c6710>
DEBUG [2023-08-16 18:44:42] httpcore.connection - start_tls.started ssl_context=<ssl.SSLContext object at 0x7f800365b0c0> server_hostname='www.example.com' timeout=5.0
DEBUG [2023-08-16 18:44:42] httpcore.connection - start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f80034c6770>
DEBUG [2023-08-16 18:44:42] httpcore.http11 - send_request_headers.started request=<Request [b'GET']>
DEBUG [2023-08-16 18:44:42] httpcore.http11 - send_request_headers.complete
DEBUG [2023-08-16 18:44:42] httpcore.http11 - send_request_body.started request=<Request [b'GET']>
DEBUG [2023-08-16 18:44:42] httpcore.http11 - send_request_body.complete
DEBUG [2023-08-16 18:44:42] httpcore.http11 - receive_response_headers.started request=<Request [b'GET']>
DEBUG [2023-08-16 18:44:42] httpcore.http11 - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Encoding', b'gzip'), (b'Accept-Ranges', b'bytes'), (b'Age', b'8177'), (b'Cache-Control', b'max-age=604800'), (b'Content-Type', b'text/html; ch
arset=UTF-8'), (b'Date', b'Wed, 16 Aug 2023 16:44:42 GMT'), (b'Etag', b'"3147526947"'), (b'Expires', b'Wed, 23 Aug 2023 16:44:42 GMT'), (b'Last-Modified', b'Thu, 17 Oct 2019 07:18:26 GMT'), (b'Server', b'ECS (nyb/1D11)'), (b'Vary', b'Accept-Encoding'), (b'X-Cache', b'HIT')
, (b'Content-Length', b'648')])
INFO [2023-08-16 18:44:42] httpx - HTTP Request: GET https://www.example.com "HTTP/1.1 200 OK"
DEBUG [2023-08-16 18:44:42] httpcore.http11 - receive_response_body.started request=<Request [b'GET']>
DEBUG [2023-08-16 18:44:42] httpcore.http11 - receive_response_body.complete
DEBUG [2023-08-16 18:44:42] httpcore.http11 - response_closed.started
DEBUG [2023-08-16 18:44:42] httpcore.http11 - response_closed.complete
DEBUG [2023-08-16 18:44:42] httpcore.connection - close.started
DEBUG [2023-08-16 18:44:42] httpcore.connection - close.complete
```
Will fix this as soon as possible.

**Comment by unode** [comment]
Can you check if 74ddb0cbd03fb2b499721b09e001987212b53ad1 fixed it?

**Comment by ArtemIsmagilov** [comment]
Cool, good solution, perfect for debugging code!
