### ISSUE TITLE
Not correct debug mode

### ISSUE THREAD

**Issue by ArtemIsmagilov** [embl-bio-it/python-mattermost-autodriver#6]
https://github.com/embl-bio-it/python-mattermost-autodriver/issues/5#issuecomment-1680828013

debug information can be displayed as in the example https://www.python-httpx.org/logging/
 
 like this 
 Expected Result:
Careful!!
Setting debug to True, will rev

Content-Encoding', b'gzip'
Accept-Ranges', b'bytes'
Age', b'507675'
Cache-Control', b'max-age=604800'
Content-Type b'text/html; charset=UTF-8'
Date, b'Thu, 16 Mar 2023 14:36:21 GMT'
Etag', b'"3147526947+ident"'
Expires b'Thu, 23 Mar 2023 14:36:21 GMT'
Last-Modified', b'Thu, 17 Oct 2019 07:18:26 GMT' 
Server b'ECS (nyb/1D2E)')'
Vary b'Accept-Encoding'
X-Cache b'HIT'
Content-Length b'648'

**Comment by unode** [comment]
Closing in favor of the reopened #5
