### ISSUE TITLE
error pip install -r requirements.txt with python3.12

### ISSUE THREAD

**Issue by ArtemIsmagilov** [embl-bio-it/python-mattermost-autodriver#9]
Error installing dependent packages with python3.12.
The console says that aiohttp does not support python3.12

**Comment by unode** [comment]
An upstream problem with aiohttp. See https://github.com/aio-libs/aiohttp/issues/7739
Fixing with the suggestion of pinning 3.9.0b0.

**Comment by ArtemIsmagilov** [comment]
thanks)
